// Code generated by "stringer -type=Phase,Suit,Rank -linecomment"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PhaseInit-0]
	_ = x[PhaseDeal-1]
	_ = x[PhaseAuction-2]
	_ = x[PhaseTalonExchange-3]
	_ = x[PhasePlay-4]
	_ = x[PhaseScoring-5]
	_ = x[PhaseHandEnd-6]
}

const _Phase_name = "initdealauctiontalon exchangeplayscoringhand end"

var _Phase_index = [...]uint8{0, 4, 8, 15, 29, 33, 40, 48}

func (i Phase) String() string {
	if i < 0 || i >= Phase(len(_Phase_index)-1) {
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spades-0]
	_ = x[Clubs-1]
	_ = x[Diamonds-2]
	_ = x[Hearts-3]
}

const _Suit_name = "♠️♣️♦️♥️"

var _Suit_index = [...]uint8{0, 6, 12, 18, 24}

func (i Suit) String() string {
	if i < 0 || i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nine-0]
	_ = x[Jack-1]
	_ = x[Queen-2]
	_ = x[King-3]
	_ = x[Ten-4]
	_ = x[Ace-5]
}

const _Rank_name = "9JQK10A"

var _Rank_index = [...]uint8{0, 1, 2, 3, 4, 6, 7}

func (i Rank) String() string {
	if i < 0 || i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
